# Generated by Django 6.1.1 on 2026-09-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('new', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack')], max_length=255)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Midweight', 'Midweight'), ('Senior', 'Senior')], max_length=255)),
                ('postedAt', models.DateTimeField(auto_now_add=True)),
                ('contract', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.language')),
                ('tools', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.tool')),
            ],
        ),
    ]
