# Generated by Django 6.1.1 on 2026-09-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='languages',
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Midweight', 'Midweight'), ('Senior', 'Senior'), ('Rocket Science', 'Rocket Science')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='job',
            name='tools',
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.ManyToManyField(to='jobs.language'),
        ),
        migrations.AddField(
            model_name='job',
            name='tools',
            field=models.ManyToManyField(to='jobs.tool'),
        ),
    ]
